print("studets registration")
name =  input("enter your name:")
age =  int(input("enter your age:"))
course = input("enter your course")
persentage = float(input("enter your persentage:"))
print("studets details")
print("name:",name)
print("age",age)
print("course",course)
print("persentage",persentage)
print(type(name))
print(type(age))
print(type(course))
print(type(persentage))
print("name id ;",id(name))
print("age id :",id(age))
